Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2024-09, with the labels that each got.

#1305 New azure pipelines
  azure-pipelines-dev.yml
  azure-pipelines-release.yml
Labels: improvement

#1309 Push to registry on PR
  .github/workflows/build.yml
Labels: fix

#1310 Explicitly set 'push: true' to actually push the image
  .github/workflows/build.yml
Labels: fix

#1308 Update to Django 5.1.
  poetry.lock
  pyproject.toml
  tilavarauspalvelu/settings.py
Labels: dependencies, improvement

#1307 ReservationUnit reservation begins/ends doesn't affect published filter
  api/graphql/types/unit/filtersets.py
  tests/test_graphql_api/test_unit/test_filtering.py
Labels: fix

#1320 Add better `__str__` methods to permissions models
  permissions/models/general_role.py
  permissions/models/unit_role.py
Labels: improvement

#1321 Don't show units to the notification manager with perms filter
  api/graphql/types/unit/filtersets.py
Labels: fix

#1326 Update the permissions migration to look at role names
  permissions/migrations/0029_migrate_permissions_to_new_models.py
Labels: fix

#1327 Django Admin: Add missing payment_product field in ReservationUnitAdmin
  reservation_units/admin/reservation_unit/admin.py
Labels: fix

#1329 Add a better celery health check
  tilavarauspalvelu/celery.py
Labels: fix

#1322 Update django-environment-config to 0.2.1
  poetry.lock
  pyproject.toml
  tilavarauspalvelu/settings.py
Labels: fix, dependencies

#1332 Fix reservation user not being saved on create
  api/graphql/types/reservation/serializers/create_serializers.py
Labels: fix

#1335 Check GDPR API JWT `loa` claim in permission checks
  api/gdpr/views.py
  tests/test_gdpr_api/__init__.py
  tests/test_gdpr_api/helpers.py
  tests/test_gdpr_api/test_gdpr_api.py
  tests/test_helauth/helpers.py
Labels: improvement

#1350 Add new environment for pod deployment mod hooks
  tilavarauspalvelu/settings.py
Labels: fix

#1349 Django Admin: Fix removing empty timeslots
  reservation_units/admin/reservation_unit/form.py
Labels: fix

#1351 Match emails case-insensitively in Tunnistamo -> Keycloak migration
  users/helauth/pipeline.py
Labels: fix

#1358 Log HelsinkiProfileClient exceptions to sentry
  users/helauth/clients.py
  users/helauth/pipeline.py
  utils/sentry.py
Labels: improvement

#1360 Add better logging for permission errors in GDPR requests
  api/gdpr/views.py
  tests/test_gdpr_api/test_gdpr_api.py
Labels: improvement

#1361 Change to correct `API_AUTHORIZATION_FIELD` & dump claims to sentry data
  api/gdpr/views.py
  tests/test_gdpr_api/helpers.py
  tests/test_gdpr_api/test_gdpr_api.py
  tilavarauspalvelu/settings.py
Labels: fix
