Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2024-10, with the labels that each got.

#1342 [2.2] Migrate terms of use models to the new app
  applications/admin/application_round/form.py
  applications/migrations/0094_alter_applicationround_terms_of_use.py
  applications/models/application_round.py
  common/management/commands/data_creation/create_caisa.py
  common/management/commands/data_creation/create_reservation_units.py
  config/settings.py
  locale/fi/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  reservation_units/admin/reservation_unit/form.py
  reservation_units/migrations/0106_alter_reservationunit_cancellation_terms_and_more.py
  reservation_units/models/reservation_unit.py
  templates/terms_of_use/booking_terms.jinja
  templates/terms_of_use/components/base.jinja
  terms_of_use/admin/__init__.py
  terms_of_use/admin/terms_of_use.py
  terms_of_use/apps.py
  terms_of_use/migrations/0006_delete_termsofuse.py
  terms_of_use/models.py
  terms_of_use/translation.py
  tests/factories/terms_of_use.py
  tests/test_admin/test_reservation_unit_admin_terms.py
  tests/test_graphql_api/test_reservation_unit/test_query.py
  tests/test_graphql_api/test_reservation_unit/test_update_draft.py
  tests/test_graphql_api/test_reservation_unit/test_update_not_draft.py
  tests/test_rest_api/test_terms_pdf.py
  tilavarauspalvelu/admin/__init__.py
  tilavarauspalvelu/admin/terms_of_use/admin.py
  tilavarauspalvelu/api/graphql/types/terms_of_use/filtersets.py
  tilavarauspalvelu/api/graphql/types/terms_of_use/types.py
  tilavarauspalvelu/api/rest/views.py
  tilavarauspalvelu/enums.py
  tilavarauspalvelu/migrations/0004_migrate_terms_of_use.py
  tilavarauspalvelu/models/__init__.py
  tilavarauspalvelu/models/terms_of_use/actions.py
  tilavarauspalvelu/models/terms_of_use/model.py
  tilavarauspalvelu/models/terms_of_use/queryset.py
  tilavarauspalvelu/translation.py
Labels: refactor

#1344 [2.4] Migrate resource models to the new app
  common/management/commands/data_creation/create_reservables.py
  common/management/commands/data_creation/create_reservation_units.py
  locale/fi/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  reservation_units/migrations/0108_alter_reservationunit_resources.py
  reservation_units/models/reservation_unit.py
  reservation_units/querysets.py
  resources/admin.py
  resources/apps.py
  resources/enums.py
  resources/migrations/0011_delete_resource.py
  resources/models.py
  resources/translation.py
  tests/factories/resource.py
  tests/test_graphql_api/test_resource/test_create.py
  tests/test_graphql_api/test_resource/test_create_permissions.py
  tests/test_graphql_api/test_resource/test_delete.py
  tests/test_graphql_api/test_resource/test_update.py
  tilavarauspalvelu/admin/__init__.py
  tilavarauspalvelu/admin/resource/admin.py
  tilavarauspalvelu/api/graphql/types/resource/filtersets.py
  tilavarauspalvelu/api/graphql/types/resource/mutations.py
  tilavarauspalvelu/api/graphql/types/resource/permissions.py
  tilavarauspalvelu/api/graphql/types/resource/serializers.py
  tilavarauspalvelu/api/graphql/types/resource/types.py
  tilavarauspalvelu/enums.py
  tilavarauspalvelu/migrations/0006_migrate_resources.py
  tilavarauspalvelu/models/__init__.py
  tilavarauspalvelu/models/resource/actions.py
  tilavarauspalvelu/models/resource/model.py
  tilavarauspalvelu/models/resource/queryset.py
  tilavarauspalvelu/translation.py
Labels: refactor

#1369 [2.13] Move elasticsearch configs and utils to different directories
  config/elasticsearch/reservation_units.json
  config/settings.py
  elastic_django/__init__.py
  elastic_django/reservation_units/__init__.py
  elastic_django/reservation_units/tasks.py
  tests/test_utils/test_reservation_unit_query_builder.py
  tilavarauspalvelu/api/graphql/types/reservation_unit/filtersets.py
  tilavarauspalvelu/tasks.py
  utils/elasticsearch.py
Labels: refactor

#1375 Fix celery config
  Makefile
  docker/worker.sh
Labels: fix

#1378 Fix user admin page not loading due to missing read-only fields
  tilavarauspalvelu/admin/user/admin.py
Labels: fix

#1381 Set build SHA based on actual PR head sha
  .github/workflows/build.yml
Labels: fix

#1376 Fix Helsinki profile token refreshing
  tilavarauspalvelu/utils/helauth/clients.py
Labels: fix

#1395 Fix issues with staff emails
  tests/test_integrations/test_email/test_email_service.py
  tests/test_integrations/test_email/test_find_recipients.py
  tilavarauspalvelu/integrations/email/find_recipients.py
  tilavarauspalvelu/integrations/email/main.py
Labels: fix

#1397 Fix a couple of reservation admin reservation unit refs
  tilavarauspalvelu/admin/reservation/admin.py
Labels: fix

#1402 User reservation count is now only affected by NORMAL type reservations
  tests/test_graphql_api/test_reservation_unit/test_query.py
  tilavarauspalvelu/api/graphql/types/reservation_unit/types.py
  utils/date_utils.py
Labels: fix

#1401 Old pricing is hidden in GQL
  tests/test_graphql_api/test_reservation_unit/test_pricing.py
  tilavarauspalvelu/api/graphql/types/reservation_unit/serializers.py
  tilavarauspalvelu/api/graphql/types/reservation_unit_pricing/types.py
  tilavarauspalvelu/models/reservation_unit_pricing/queryset.py
Labels: improvement

#1373 Add `sent_date` as an option for ordering applications
  tilavarauspalvelu/api/graphql/types/application/filtersets.py
Labels: improvement
