Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2024-08, with the labels that each got.

#1273 Add `allow_cascade=True` to test data creation flush
  common/management/commands/data_creation/main.py
Labels: fix

#1275 Switch to ECR for pulling docker images
  docker/Dockerfile
Labels: fix

#1283 Fix creating reservation statistics when creating seasonal bookings
  actions/recurring_reservation.py
  applications/tasks.py
Labels: fix

#1284 Convert pk list to set for serialization to statistics task
  applications/tasks.py
Labels: fix

#1285 Increase ReservationNode.Meta.max_complexity to 22
  api/graphql/types/reservation/types.py
Labels: fix

#1286 Send VAT decimal part to verkkokauppa
  merchants/verkkokauppa/order/types.py
  tests/test_external_services/test_verkkokauppa/test_create_order_params.py
  tests/test_external_services/test_verkkokauppa/test_order_types.py
Labels: improvement

#1279 Fix application round application and reservation unit counts
  api/graphql/types/application_round/types.py
Labels: fix

#1233 Add reservation deny reason rank and ordering filter
  api/graphql/types/reservation_deny_reason/filtersets.py
  reservations/migrations/0078_alter_reservationdenyreason_options_and_more.py
  reservations/models/reservation_deny_reason.py
  tests/test_graphql_api/test_reservation_deny_reason/test_query.py
Labels: feature

#1272 Add migration to correct net prices on reservations
  reservations/migrations/0077_alter_reservationstatistic_reservee_type.py
  reservations/migrations/0079_fix_reservation_price_net.py
Labels: fix

#1297 Enrich metadata in dockerfile built to ghcr.io
  .github/workflows/build.yml
Labels: improvement

#1302 Fix anonymizing all identifying data
  tests/test_utils/test_anonymization.py
  users/anonymisation.py
  users/migrations/0015_anonymize.py
Labels: fix
