Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2024-05, with the labels that each got.

#1184 Remove all service sector checks from backend
  api/graphql/types/allocated_time_slot/permissions.py
  api/graphql/types/reservation/filtersets.py
  api/graphql/types/reservation_unit/filtersets.py
  api/graphql/types/reservation_unit_option/permissions.py
  api/graphql/types/unit/filtersets.py
  api/legacy_rest_api/tests/test_reservation_api.py
  api/legacy_rest_api/views.py
  permissions/getters.py
  permissions/helpers.py
  tests/test_graphql_api/test_allocated_time_slot/test_create_permissions.py
  tests/test_graphql_api/test_allocated_time_slot/test_delete_permissions.py
  tests/test_graphql_api/test_order/test_query_permissions.py
  tests/test_graphql_api/test_recurring_reservation/test_create_permissions.py
  tests/test_graphql_api/test_recurring_reservation/test_update_permissions.py
  tests/test_graphql_api/test_reservation/test_filtering.py
  tests/test_graphql_api/test_reservation/test_query.py
  tests/test_graphql_api/test_reservation/test_staff_create.py
  tests/test_graphql_api/test_reservation/test_working_memo_update.py
  tests/test_graphql_api/test_reservation_unit/test_filtering.py
  tests/test_graphql_api/test_reservation_unit_option/test_update_permissions.py
  tests/test_graphql_api/test_resource/test_create_permissions.py
  tests/test_graphql_api/test_resource/test_query_permissions.py
  tests/test_graphql_api/test_space/test_create_permissions.py
  tests/test_graphql_api/test_space/test_delete_permissions.py
  tests/test_graphql_api/test_space/test_filtering.py
  tests/test_graphql_api/test_space/test_update_permissions.py
  tests/test_graphql_api/test_unit/test_query_permissions.py
  tests/test_graphql_api/test_user/test_query_permissions.py
  tests/test_models/test_user.py
  users/models.py
Labels: refactor

#1166 Fix using default language for all staff notifications
  email_notification/helpers/email_builder_application.py
  email_notification/helpers/email_builder_reservation.py
  email_notification/helpers/email_sender.py
  email_notification/tasks.py
  tests/test_email/test_email_sender.py
Labels: improvement

#1156 Migrate old application data
  applications/migrations/0089_migrate_old_application_data.py
Labels: improvement

#1201 Fix issues in old application data migration
  applications/migrations/0089_migrate_old_application_data.py
Labels: fix

#1205 One more batch of fixes to application migration
  applications/migrations/0089_migrate_old_application_data.py
Labels: fix

#1206 Fix timezone mistakes in application migration
  applications/migrations/0089_migrate_old_application_data.py
Labels: fix

#1186 Fix issue in first reservable time calculation when duration exactly minimum
  reservation_units/utils/first_reservable_time_helper.py
  tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py
Labels: fix

#1193 Exclude `SEASONAL` type reservations from user max reservations per unit
  api/graphql/types/reservation/serializers/create_serializers.py
  api/graphql/types/reservation_unit/types.py
  tests/test_graphql_api/test_reservation/test_create.py
  tests/test_graphql_api/test_reservation_unit/test_query.py
Labels: improvement
