Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2024-11, with the labels that each got.

#1405 Fix mock verkkokauppa reverse accessor name
  tilavarauspalvelu/utils/verkkokauppa/helpers.py
Labels: fix

#1411 Add rejected occurrence unit name filter
  tilavarauspalvelu/api/graphql/types/rejected_occurrence/filtersets.py
Labels: improvement

#1413 Add `ApplicationRound` ongoing filter to the GQL endpoint
  tests/test_graphql_api/test_application_round/test_filtering.py
  tilavarauspalvelu/api/graphql/types/application_round/filtersets.py
Labels: improvement

#1414 Fix Django Admin OriginHaukiResource ReservationUnit link
  tilavarauspalvelu/admin/reservation_unit/admin.py
Labels: fix

#1415 Hide orders of deleted reservations from the GQL
  tests/test_graphql_api/test_order/test_query.py
  tilavarauspalvelu/api/graphql/schema.py
Labels: fix

#1417 Give JSON from CSRF endpoint if no `redirect_to` is given
  tilavarauspalvelu/api/rest/views.py
Labels: improvement

#1421 Update translations for permission and anonymization emails
  locale/fi/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  tests/test_integrations/test_email/test_email_service.py
  tests/test_integrations/test_email/test_permission_context.py
  tests/test_integrations/test_email/test_render_html.py
  tests/test_integrations/test_email/test_render_text.py
  tilavarauspalvelu/integrations/email/template_context/permissions.py
Labels: fix

#1423 Fix application round handled email send condition
  tests/test_integrations/test_email/test_email_service.py
  tilavarauspalvelu/models/application/queryset.py
Labels: fix

#1425 Allow resetting application rounds in `RESULT_SENT` from admin panel
  tests/factories/application.py
  tests/test_actions/test_application_round_actions.py
  tilavarauspalvelu/enums.py
  tilavarauspalvelu/models/application_round/actions.py
Labels: improvement

#1426 Add notification sent dates to past application rounds
  tilavarauspalvelu/migrations/0029_add_old_application_rounds_notification_dates.py
Labels: feature

#1424 Add endpoint for sending application round results to applicants
  tests/test_graphql_api/test_application_round/helpers.py
  tests/test_graphql_api/test_application_round/test_set_results_sent.py
  tilavarauspalvelu/api/graphql/extensions/error_codes.py
  tilavarauspalvelu/api/graphql/mutations.py
  tilavarauspalvelu/api/graphql/schema.py
  tilavarauspalvelu/api/graphql/types/application_round/mutation.py
  tilavarauspalvelu/api/graphql/types/application_round/serializers.py
Labels: feature

#1428 Add recurring reservation deny mutation endpoint
  tests/factories/recurring_reservation.py
  tests/test_graphql_api/test_recurring_reservation/helpers.py
  tests/test_graphql_api/test_recurring_reservation/test_deny_series.py
  tests/test_graphql_api/test_recurring_reservation/test_deny_series_permissions.py
  tests/test_graphql_api/test_recurring_reservation/test_reschedule_series.py
  tests/test_graphql_api/test_recurring_reservation/test_reschedule_series_permissions.py
  tests/test_graphql_api/test_recurring_reservation/test_update_series_permissions.py
  tilavarauspalvelu/api/graphql/extensions/error_codes.py
  tilavarauspalvelu/api/graphql/mutations.py
  tilavarauspalvelu/api/graphql/schema.py
  tilavarauspalvelu/api/graphql/types/recurring_reservation/mutations.py
  tilavarauspalvelu/api/graphql/types/recurring_reservation/permissions.py
  tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers.py
  tilavarauspalvelu/api/graphql/types/reservation/permissions.py
  tilavarauspalvelu/utils/permission_resolver.py
Labels: fix, feature

#1430 Add application section recurring reservation mass cancel endpoint
  tests/test_graphql_api/test_recurring_reservation/helpers.py
  tests/test_graphql_api/test_recurring_reservation/test_cancel_series.py
  tests/test_graphql_api/test_recurring_reservation/test_cancel_series_permissions.py
  tilavarauspalvelu/api/graphql/extensions/error_codes.py
  tilavarauspalvelu/api/graphql/mutations.py
  tilavarauspalvelu/api/graphql/schema.py
  tilavarauspalvelu/api/graphql/types/application_section/mutations.py
  tilavarauspalvelu/api/graphql/types/application_section/permissions.py
  tilavarauspalvelu/api/graphql/types/application_section/serializers.py
Labels: feature

#1435 Fix paths for new monitoring endpoints
  config/urls.py
Labels: fix

#1436 Switch redis health check for custom sentinel check
  config/health_checks.py
  config/settings.py
Labels: fix

#1437 Dependency cleanup & add poetry pre-commit hooks
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docker/Dockerfile
  poetry.lock
  pyproject.toml
  tilavarauspalvelu/enums.py
  tilavarauspalvelu/templatetags/tilavarauspalvelu.py
Labels: improvement

#1434 Add task to delete old applications
  config/settings.py
  tests/test_tasks/test_delete_expired_applications.py
  tilavarauspalvelu/tasks.py
Labels: feature

#1443 Improve github workflows
  .github/pr-labeler.yml
  .github/release.yml
  .github/workflows/build.yml
  .github/workflows/fast_forward.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/pull_request.yml
  .github/workflows/test.yml
Labels: improvement

#1400 Move project to python 3.13
  .github/workflows/test.yml
  config/settings.py
  docker/Dockerfile
  poetry.lock
  pyproject.toml
Labels: python, improvement

#1444 Enable test data generation without mock verkkokauppa enabled
  tests/factories/payment_order.py
  tests/helpers.py
  tests/test_utils/test_create_test_data.py
Labels: fix

#1445 Fix not allowing blank details on mass reservation cancel and deny endpoints
  tilavarauspalvelu/api/graphql/types/application_section/serializers.py
  tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers.py
Labels: fix

#1447 Fix `anonymize_old_users_task` task name
  tilavarauspalvelu/tasks.py
Labels: fix

#1448 Refactor CSV exports
  docker/Dockerfile
  tests/test_csv_exporters/helpers.py
  tests/test_csv_exporters/test_application_round_applications_export.py
  tests/test_csv_exporters/test_application_round_results_export.py
  tests/test_csv_exporters/test_reservation_unit_export.py
  tilavarauspalvelu/admin/application_round/admin.py
  tilavarauspalvelu/admin/request_log/admin.py
  tilavarauspalvelu/admin/reservation_unit/admin.py
  tilavarauspalvelu/services/csv_export/__init__.py
  tilavarauspalvelu/services/csv_export/_base_exporter.py
  tilavarauspalvelu/services/csv_export/application_round_applications_exporter.py
  tilavarauspalvelu/services/csv_export/application_round_result_exporter.py
  tilavarauspalvelu/services/csv_export/reservation_unit_exporter.py
  tilavarauspalvelu/services/csv_export/sql_log_exporter.py
  tilavarauspalvelu/utils/exporter/__init__.py
  tilavarauspalvelu/utils/exporter/application_round_applications_exporter.py
  tilavarauspalvelu/utils/exporter/application_round_result_exporter.py
  tilavarauspalvelu/utils/exporter/base_exporter.py
  tilavarauspalvelu/utils/exporter/sql_log_exporter.py
  tilavarauspalvelu/utils/reservation_units/__init__.py
  tilavarauspalvelu/utils/reservation_units/export_data.py
  utils/date_utils.py
Labels: fix

#1454 Remove celery ping health check due to unreliability
  config/settings.py
Labels: fix
