Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2025-06, with the labels that each got.

#1805 Refactor Show all container to use grid
  apps/admin-ui/src/component/ReservationTypeForm.tsx
  apps/admin-ui/src/spa/application-rounds/[id]/allocation/AllocationColumn.tsx
  apps/admin-ui/src/spa/application-rounds/[id]/allocation/index.tsx
  apps/admin-ui/src/spa/reservation-units/Filters.tsx
  apps/admin-ui/src/spa/reservations/Filters.tsx
  apps/ui/components/recurring/SeasonalSearchForm.tsx
  apps/ui/components/search/SingleSearchForm.tsx
  apps/ui/components/search/styled.ts
  packages/common/src/components/IconButton.tsx
  packages/common/src/components/ShowAllContainer.tsx
  packages/common/styled/util.ts
Labels: refactor

#1852 Allow external/guest AD superusers to make reservations/applications
  backend/tests/factories/user.py
  backend/tests/test_graphql_api/test_application/test_create.py
  backend/tests/test_graphql_api/test_application/test_send.py
  backend/tests/test_graphql_api/test_reservation/test_adjust_time.py
  backend/tests/test_graphql_api/test_reservation/test_create.py
  backend/tilavarauspalvelu/models/user/validators.py
Labels: fix

#1851 Fix sentry source map generation codegen
  .github/workflows/upload_sentry_sourcemaps.yml
Labels: fix

#1853 Fix allocation page mobile layout breaking
  apps/admin-ui/src/spa/application-rounds/[id]/allocation/ApplicationEventCard.tsx
  apps/admin-ui/src/spa/application-rounds/[id]/allocation/ApplicationEvents.tsx
Labels: fix

#1854 Fix application show rejected if locked from allocation
  apps/admin-ui/src/spa/applications/[id]/index.tsx
Labels: fix

#1865 Refactor remove duplicated Reservee info component
  apps/ui/components/reservation/ReservationInfoSection.tsx
  apps/ui/components/reservation/index.ts
  apps/ui/pages/reservations/[id]/confirmation.tsx
  apps/ui/pages/reservations/[id]/index.tsx
Labels: refactor

#1875 Remove billing information from reservations
  backend/locale/fi/LC_MESSAGES/django.po
  backend/locale/sv/LC_MESSAGES/django.po
  backend/tests/factories/reservation.py
  backend/tests/factories/reservation_metadata_field.py
  backend/tests/test_actions/test_anonymization.py
  backend/tests/test_actions/test_application_round/test_generate_reservations_from_allocations.py
  backend/tests/test_gdpr_api/test_gdpr_api.py
  backend/tests/test_graphql_api/test_reservation/test_query.py
  backend/tests/test_graphql_api/test_reservation/test_query_permissions.py
  backend/tests/test_graphql_api/test_reservation/test_staff_create.py
  backend/tests/test_graphql_api/test_reservation/test_update.py
  backend/tests/test_graphql_api/test_reservation_series/test_create_series.py
  backend/tests/test_graphql_api/test_reservation_series/test_update_series.py
  backend/tests/test_graphql_api/test_reservation_unit/test_query_permissions.py
  backend/tilavarauspalvelu/admin/reservation/admin.py
  backend/tilavarauspalvelu/admin/reservation/form.py
  backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_create_serializers.py
  backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_reservation_modify_serializers.py
  backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/update_serializers.py
  backend/tilavarauspalvelu/api/graphql/types/reservation/types.py
  backend/tilavarauspalvelu/api/graphql/types/reservation_series/serializers/create_serializer.py
  backend/tilavarauspalvelu/api/graphql/types/reservation_series/serializers/reschedule_serializer.py
  backend/tilavarauspalvelu/api/graphql/types/reservation_series/serializers/update_serializer.py
  backend/tilavarauspalvelu/management/commands/data_creation/create_reservation_related_things.py
  backend/tilavarauspalvelu/migrations/0145_remove_reservation_billing_address_city_and_more.py
  backend/tilavarauspalvelu/migrations/0146_migrate_metadata_fields.py
  backend/tilavarauspalvelu/models/application_round/actions.py
  backend/tilavarauspalvelu/models/reservation/model.py
  backend/tilavarauspalvelu/models/user/actions.py
  backend/tilavarauspalvelu/typing.py
  tilavaraus.graphql
Labels: refactor, breaking
