Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2025-02, with the labels that each got.

#1515 Update reservation access types with reservation unit access type
  tests/test_graphql_api/test_reservation_unit/test_update_not_draft.py
  tilavarauspalvelu/admin/reservation_unit/form.py
  tilavarauspalvelu/api/graphql/extensions/error_codes.py
  tilavarauspalvelu/api/graphql/types/reservation_unit/serializers.py
  tilavarauspalvelu/models/reservation_unit/actions.py
Labels: feature

#1517 Add `.test-durations` to artifacts instead of creating pull requests
  .github/workflows/test.yml
  .github/workflows/update_test_durations.yml
  .test_durations
Labels: improvement

#1521 Fix artifact download for test durations
  .github/workflows/test.yml
Labels: fix

#1522 Fix FRONTEND_TESTING_API_ENABLED setting for Local and Docker envs
  config/settings.py
Labels: fix

#1524 Fix invalid artifact name for coverage results
  .github/workflows/test.yml
Labels: fix

#1526 Update created at when adding new reservation to series
  tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers.py
Labels: fix

#1528 Fix frontend testing API in Docker environment
  .dockerignore
  docker-compose.yml
Labels: fix

#1529 Only delete tentative reservation from Pindora if using access code
  backend/tilavarauspalvelu/api/graphql/types/reservation/mutations.py
Labels: fix

#1536 replace: cookiehub with HDS cookie-consent
  apps/ui/.env.local.example
  apps/ui/README.md
  apps/ui/components/ExternalScripts.tsx
  apps/ui/modules/const.ts
  apps/ui/modules/serverUtils.ts
  apps/ui/pages/_app.tsx
  apps/ui/pages/sitesettings.json
Labels: feature

#1554 fix: matomo tracking
  apps/ui/components/ExternalScripts.tsx
Labels: fix

#1560 fix: external script loading
  apps/ui/components/ExternalScripts.tsx
  apps/ui/pages/_app.tsx
  apps/ui/public/init-matomo.js
Labels: fix

#1562 fix: matomo script name
  apps/ui/public/init-matomo.js
Labels: fix

#1563 fix: script routes getting localized
  apps/ui/components/ExternalScripts.tsx
  apps/ui/public/scripts/init-matomo.js
Labels: fix

#1567 fix: incorrect translation key for pay button
  apps/ui/components/reservation/Step1.tsx
Labels: fix

#1557 Allow empty working memo in reservation memo update
  backend/tests/test_graphql_api/test_reservation/test_working_memo_update.py
  backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/memo_serializers.py
Labels: fix

#1590 fix: middleware checks for regular users
  apps/ui/middleware.ts
Labels: fix

#1606 Change dependabot to weekly schedule
  .github/dependabot.yml
Labels: fix

#1595 Add filtering to Report APIs
  backend/tests/test_rest_api/test_reservation_statistics_export.py
  backend/tests/test_rest_api/test_reservation_unit_export.py
  backend/tilavarauspalvelu/api/rest/utils.py
  backend/tilavarauspalvelu/api/rest/views.py
  backend/tilavarauspalvelu/services/export/_base_exporter.py
  backend/tilavarauspalvelu/services/export/reservation_unit_exporter.py
Labels: feature

#1596 Use consistent `reservee_name` implementation
  backend/tilavarauspalvelu/api/graphql/types/reservation/filtersets.py
Labels: fix

#1609 Add `CORS_ALLOWED_ORIGIN_REGEXES`
  backend/config/settings.py
Labels: fix, feature

#1612 Fix access type `end_date`
  backend/tilavarauspalvelu/models/reservation_unit_access_type/model.py
Labels: fix
