Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2025-09, with the labels that each got.

#1960 Only use `NowTT` when in automated testing environment
  backend/config/settings.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tilavarauspalvelu/api/graphql/types/application_section/serializers.py
  backend/tilavarauspalvelu/migrations/0014_migrate_common.py
  backend/tilavarauspalvelu/migrations/0019_add_now_tt.py
  backend/tilavarauspalvelu/migrations/0148_affecting_reservations_now_tt_split.py
  backend/tilavarauspalvelu/models/application/model.py
  backend/tilavarauspalvelu/models/application_round/model.py
  backend/tilavarauspalvelu/models/application_section/model.py
  backend/tilavarauspalvelu/models/application_section/queryset.py
  backend/tilavarauspalvelu/models/banner_notification/queryset.py
  backend/tilavarauspalvelu/models/reservation_series/queryset.py
  backend/tilavarauspalvelu/models/reservation_unit/model.py
  backend/tilavarauspalvelu/models/reservation_unit/queryset.py
  backend/utils/db.py
Labels: fix

#1961 Count "high" as strong login from ID token
  backend/tests/factories/user.py
  backend/tilavarauspalvelu/dataclasses.py
Labels: fix

#1958 Add local mocking to Pindora client
  backend/config/settings.py
  backend/local_settings_example.py
  backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_reservation.py
  backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_reservation_series.py
  backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_reservation_unit.py
  backend/tests/test_integrations/test_keyless_entry/test_pindora_client/test_seasonal_booking.py
  backend/tilavarauspalvelu/integrations/keyless_entry/client.py
  backend/tilavarauspalvelu/integrations/keyless_entry/exceptions.py
Labels: feature

#1962 Add search by `ext_uuid` to admin panel views
  backend/locale/fi/LC_MESSAGES/django.po
  backend/locale/sv/LC_MESSAGES/django.po
  backend/tilavarauspalvelu/admin/application_section/admin.py
  backend/tilavarauspalvelu/admin/reservation/admin.py
  backend/tilavarauspalvelu/admin/reservation_series/admin.py
  backend/tilavarauspalvelu/admin/reservation_unit/admin.py
Labels: improvement

#1964 Fix error code returned by application create age validation
  backend/tilavarauspalvelu/api/graphql/types/application/serializers.py
Labels: fix

#1985 Update reservation form translations
  backend/locale/fi/LC_MESSAGES/django.po
  backend/locale/sv/LC_MESSAGES/django.po
  backend/tilavarauspalvelu/enums.py
  backend/tilavarauspalvelu/migrations/0149_alter_reservationunit_reservation_form.py
  tilavaraus.graphql
Labels: improvement

#1984 Add script for creating robot test data
  backend/config/settings.py
  backend/config/urls.py
  backend/tests/test_rest_api/test_create_robot_test_data.py
  backend/tilavarauspalvelu/api/rest/utils.py
  backend/tilavarauspalvelu/api/rest/views.py
  backend/tilavarauspalvelu/management/commands/create_robot_test_data.py
Labels: feature

#1988 Create robot data without using factories
  backend/tests/test_rest_api/test_create_robot_test_data.py
  backend/tilavarauspalvelu/management/commands/create_robot_test_data.py
Labels: fix

#1954 Fix reservationsMaxDaysBefore validation in Admin UI
  apps/admin-ui/src/lib/reservation-units/[pk]/form.ts
Labels: fix

#2018 Refactor cleaner preview link using styled component
  apps/admin-ui/src/lib/reservation-units/[pk]/BottomButtonsStripe.tsx
  apps/ui/components/common/ButtonLikeLink.tsx
  packages/common/styled/buttonCss.ts
Labels: refactor

#2024 Override field permission checks in reservation node
  backend/tests/test_graphql_api/test_reservation/test_query.py
  backend/tilavarauspalvelu/api/graphql/extensions/utils.py
Labels: fix

#2025 Fix missing `distinct=True` on filters
  backend/tilavarauspalvelu/api/graphql/types/application_round/queries/filtersets.py
  backend/tilavarauspalvelu/api/graphql/types/rejected_occurrence/queries/filtersets.py
  backend/tilavarauspalvelu/api/graphql/types/reservation_unit/queries/filtersets.py
  backend/tilavarauspalvelu/api/graphql/types/resource/queries/filtersets.py
  backend/tilavarauspalvelu/api/graphql/types/space/queries/filtersets.py
Labels: fix

#2029 Add handled due by date to cancel email if not paid
  backend/templates/email/html/reservation_cancelled.jinja
  backend/templates/email/text/reservation_cancelled.jinja
  backend/tests/test_integrations/test_email/test_email_types/test_reservation_cancelled.py
  backend/tilavarauspalvelu/integrations/email/template_context/reservation.py
  backend/tilavarauspalvelu/integrations/email/typing.py
Labels: feature

#1997 Add reservation unit pricing material price
  backend/tests/factories/reservation_unit_pricing.py
  backend/tilavarauspalvelu/admin/reservation_unit/form.py
  backend/tilavarauspalvelu/admin/reservation_unit_pricing/admin.py
  backend/tilavarauspalvelu/api/graphql/types/reservation/queries/types.py
  backend/tilavarauspalvelu/api/graphql/types/reservation_unit/mutations/create_reservation_unit.py
  backend/tilavarauspalvelu/api/graphql/types/reservation_unit/mutations/update_reservation_unit.py
  backend/tilavarauspalvelu/api/graphql/types/reservation_unit_pricing/queries/types.py
  backend/tilavarauspalvelu/management/commands/data_creation/create_reservation_units.py
  backend/tilavarauspalvelu/management/commands/data_creation/utils.py
  backend/tilavarauspalvelu/migrations/0154_reservationunitpricing_material_price_and_more.py
  backend/tilavarauspalvelu/models/reservation_unit_pricing/model.py
  backend/tilavarauspalvelu/translation.py
  tilavaraus.graphql
Labels: feature

#2004 Don't show inactive permissions through the GraphQL API
  backend/tests/test_graphql_api/test_user/test_current_user.py
  backend/tilavarauspalvelu/api/graphql/types/user/queries/types.py
Labels: fix

#2014 Make terms of use on application round required in Django admin
  backend/tilavarauspalvelu/admin/application_round/admin.py
  backend/tilavarauspalvelu/admin/application_round/form.py
Labels: fix

#2034 Fix few final errors in robot test data generation
  backend/tilavarauspalvelu/management/commands/create_robot_test_data.py
Labels: fix

#2032 Fix missing column name in reservation unit export
  backend/tilavarauspalvelu/services/export/reservation_unit_exporter.py
Labels: fix

#2042 Update `django-subforms`
  backend/poetry.lock
  backend/pyproject.toml
Labels: fix

#2057 Fix SonarCloud upload in main branch, again
  .github/workflows/test-backend.yml
Labels: fix

#2083 Fix mid-hook database setting
  backend/config/settings.py
Labels: fix
