Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2025-05, with the labels that each got.

#1762 Fix reservation unit cant be scheduled
  apps/admin-ui/src/helpers/date.ts
  apps/admin-ui/src/spa/ReservationUnit/edit/form.ts
Labels: fix

#1785 Fix backend directory paths for dependabot
  .github/dependabot.yml
Labels: github_actions

#1756 Block users from accessing ApplicationRound page when they shouldn't
  apps/ui/gql/gql-types.ts
  apps/ui/pages/recurring/[id]/index.tsx
Labels: fix

#1760 add: unit name to be shown along reservation unit name
  apps/ui/components/application/ApprovedReservations.tsx
  apps/ui/gql/gql-types.ts
  apps/ui/public/locales/en/application.json
  apps/ui/public/locales/fi/application.json
  apps/ui/public/locales/sv/application.json
Labels: feature

#1782 Fix flaky test during midnight
  apps/ui/modules/reservationUnit.test.ts
Labels: fix

#1773 Fix duplicate fields in application text search
  backend/tilavarauspalvelu/api/graphql/types/application/filtersets.py
Labels: fix

#1745 Only count reservations that are going to occur for series used access types
  backend/tests/test_models/test_recurring_reservation.py
  backend/tilavarauspalvelu/models/recurring_reservation/model.py
Labels: fix

#1792 Fix allocation page going to infinite rerender loop
  apps/admin-ui/src/spa/application-rounds/[id]/allocation/index.tsx
Labels: fix

#1759 fix: show only reservable checkbox
  apps/ui/components/search/SingleSearchForm.tsx
  apps/ui/modules/search.ts
Labels: fix

#1764 fix: recurring reservations starting bottom banner position
  apps/ui/components/recurring/StartApplicationBar.tsx
  apps/ui/pages/recurring/[id]/index.tsx
  apps/ui/styles/variables.css
Labels: fix, improvement

#1768 fix: admin Card links
  apps/admin-ui/src/spa/unit/[id]/ReservationUnitCard.tsx
  packages/common/src/components/Card.tsx
Labels: fix

#1769 fix: make the purpose text able to wrap in view application page
  apps/ui/components/application/ApplicationSectionList.tsx
  apps/ui/components/application/styled.tsx
Labels: fix

#1789 add: Make single reservation button to admin my-units view
  apps/admin-ui/src/i18n/messages.ts
  apps/admin-ui/src/spa/my-units/[id]/CreateReservationModal.tsx
  apps/admin-ui/src/spa/my-units/[id]/ReservationUnitCalendarView.tsx
  apps/admin-ui/src/spa/my-units/[id]/UnitCalendar.tsx
  apps/admin-ui/src/spa/my-units/[id]/UnitReservations.tsx
  apps/admin-ui/src/spa/my-units/[id]/index.tsx
Labels: feature, refactor

#1761 Fix missing too many reservations error translation
  apps/ui/components/reservation-unit/Images.tsx
  apps/ui/components/reservation-unit/ReservationInfoContainer.tsx
  apps/ui/pages/reservation-unit/[id].tsx
  packages/common/src/helpers.test.ts
  packages/common/src/helpers.ts
Labels: fix, improvement

#1793 Refactor application-round single page
  apps/admin-ui/gql/gql-types.ts
  apps/admin-ui/src/spa/application-rounds/[id]/index.tsx
  apps/admin-ui/src/spa/application-rounds/[id]/review/ReviewEndAllocation.tsx
  apps/admin-ui/src/spa/application-rounds/[id]/review/index.tsx
Labels: refactor

#1808 Create payment orders when approving paid reservations
  backend/config/settings.py
  backend/tests/factories/reservation_unit.py
  backend/tests/test_graphql_api/test_reservation/test_approve.py
  backend/tests/test_graphql_api/test_reservation/test_approve_permissions.py
  backend/tilavarauspalvelu/api/graphql/extensions/error_codes.py
  backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/approve_serializers.py
  backend/tilavarauspalvelu/api/graphql/types/reservation/serializers/confirm_serializers.py
  backend/tilavarauspalvelu/enums.py
  backend/tilavarauspalvelu/models/reservation/actions.py
  backend/tilavarauspalvelu/typing.py
Labels: feature

#1812 Add endpoint for paying pending reservations in verkkokauppa
  backend/config/urls.py
  backend/tests/factories/reservation.py
  backend/tests/test_rest_api/test_redirect_to_verkkokauppa.py
  backend/tilavarauspalvelu/api/rest/utils.py
  backend/tilavarauspalvelu/api/rest/views.py
  backend/tilavarauspalvelu/enums.py
  backend/tilavarauspalvelu/models/payment_order/model.py
  backend/utils/utils.py
Labels: feature
