Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2025-01, with the labels that each got.

#1482 Fix two tests that broke after new year change
  tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py
Labels: fix

#1465 Raise error from helsinki profile endpoint if Keycloack token has expired
  tests/test_graphql_api/test_helsinki_profile/test_query.py
  tilavarauspalvelu/api/graphql/extensions/error_codes.py
  tilavarauspalvelu/api/graphql/schema.py
  tilavarauspalvelu/api/graphql/types/helsinki_profile/types.py
Labels: feature

#1483 Check path for unauthenticated user when selecting search language
  tests/test_graphql_api/test_reservation_unit/test_text_search.py
  utils/utils.py
Labels: improvement

#1486 Add Reservation Unit persons allowed filter
  tests/test_graphql_api/test_reservation_unit/test_filtering.py
  tilavarauspalvelu/api/graphql/types/reservation_unit/filtersets.py
Labels: improvement

#1488 Fix bug in sending email for reservation series with multiple weekdays
  tilavarauspalvelu/integrations/email/template_context/common.py
Labels: fix

#1492 Create series reservations as BEHALF instead of NORMAL
  tilavarauspalvelu/management/commands/data_creation/create_reservations.py
Labels: fix

#1487 Split helsinki tunnistus and helsinki profile integrations
  tests/factories/helsinki_profile.py
  tests/test_graphql_api/test_helsinki_profile/test_query.py
  tests/test_graphql_api/test_reservation/helpers.py
  tests/test_graphql_api/test_reservation/test_create.py
  tests/test_graphql_api/test_user/test_query_current_user.py
  tests/test_helauth/test_pipeline_additions.py
  tests/test_helauth/test_profile_client.py
  tests/test_utils/test_jwt_decoding.py
  tilavarauspalvelu/api/graphql/schema.py
  tilavarauspalvelu/api/graphql/types/helsinki_profile/types.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/create_serializer.py
  tilavarauspalvelu/dataclasses.py
  tilavarauspalvelu/integrations/helauth/clients.py
  tilavarauspalvelu/integrations/helauth/pipeline.py
  tilavarauspalvelu/integrations/helauth/typing.py
  tilavarauspalvelu/integrations/helauth/utils.py
  tilavarauspalvelu/integrations/helsinki_profile/__init__.py
  tilavarauspalvelu/integrations/helsinki_profile/clients.py
  tilavarauspalvelu/integrations/helsinki_profile/parsers.py
  tilavarauspalvelu/integrations/helsinki_profile/typing.py
  tilavarauspalvelu/models/user/model.py
  tilavarauspalvelu/typing.py
  utils/utils.py
Labels: refactor

#1493 Add custom Storage to convert non-ASCII filenames to ASCII
  config/settings.py
  config/storage.py
Labels: fix

#1494 Fix removing extra newlines in database migration
  tilavarauspalvelu/migrations/0063_clean_newlines_from_rich_text_fields.py
Labels: fix

#1500 Fix one translation in admin panel
  locale/fi/LC_MESSAGES/django.po
Labels: fix

#1501 Update text search language detection to look at referer header
  utils/utils.py
Labels: improvement

#1504 Don't use prefixed uWSGI settings due to `strict: true`
  docker/uwsgi.yml
Labels: fix

#1505 Create access code for staff reservations
  tests/test_graphql_api/test_reservation/test_staff_create.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_create_serializers.py
Labels: feature

#1506 Add reservation access code (de)activation calls
  tests/test_graphql_api/test_reservation/test_approve.py
  tests/test_graphql_api/test_reservation/test_confirm.py
  tests/test_graphql_api/test_reservation/test_requires_handling.py
  tests/test_graphql_api/test_reservation/test_staff_modify.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/approve_serializers.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/confirm_serializers.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/requires_handling_serializers.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_reservation_modify_serializers.py
  tilavarauspalvelu/models/payment_order/actions.py
  tilavarauspalvelu/typing.py
Labels: feature

#1507 Update access code in Pindora on reservation reschedule
  tests/test_graphql_api/test_reservation/test_adjust_time.py
  tests/test_graphql_api/test_reservation/test_staff_adjust_time.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/adjust_time_serializers.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_adjust_time_serializers.py
  tilavarauspalvelu/models/reservation/actions.py
  tilavarauspalvelu/typing.py
Labels: feature

#1509 Delete access code on cancellation, delete, deny, or inactive prune
  tests/factories/reservation.py
  tests/test_graphql_api/test_reservation/test_cancel.py
  tests/test_graphql_api/test_reservation/test_delete.py
  tests/test_graphql_api/test_reservation/test_deny.py
  tests/test_tasks/test_prune_inactive_reservations.py
  tests/test_tasks/test_prune_reservation_with_inactive_payments.py
  tilavarauspalvelu/api/graphql/types/reservation/mutations.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/cancellation_serializers.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/deny_serializers.py
  tilavarauspalvelu/models/recurring_reservation/queryset.py
  tilavarauspalvelu/models/reservation/queryset.py
  tilavarauspalvelu/models/reservation_statistic/queryset.py
  tilavarauspalvelu/services/pruning.py
  tilavarauspalvelu/tasks.py
  tilavarauspalvelu/typing.py
Labels: feature

#1510 Add Pindora info to Reservation API
  tests/test_graphql_api/test_reservation/test_query.py
  tilavarauspalvelu/api/graphql/types/reservation/types.py
  utils/date_utils.py
Labels: feature

#1499 Remove reservee language from reservations
  locale/fi/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  tests/factories/reservation.py
  tests/test_external_services/test_verkkokauppa/test_create_order_params.py
  tests/test_external_services/test_verkkokauppa/test_helpers.py
  tests/test_graphql_api/test_recurring_reservation/test_create_series.py
  tests/test_graphql_api/test_recurring_reservation/test_update_series.py
  tests/test_graphql_api/test_reservation/test_confirm.py
  tests/test_integrations/test_email/test_find_language.py
  tests/test_integrations/test_email/test_find_recipients.py
  tests/test_models/test_reservation_statistics.py
  tests/test_querysets/test_reservation_querysets.py
  tilavarauspalvelu/admin/reservation/admin.py
  tilavarauspalvelu/admin/reservation/form.py
  tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/staff_reservation_modify_serializers.py
  tilavarauspalvelu/enums.py
  tilavarauspalvelu/integrations/email/find_language.py
  tilavarauspalvelu/integrations/verkkokauppa/helpers.py
  tilavarauspalvelu/management/commands/data_creation/create_reservations.py
  tilavarauspalvelu/migrations/0064_remove_reservation_reservee_language.py
  tilavarauspalvelu/models/recurring_reservation/actions.py
  tilavarauspalvelu/models/reservation/actions.py
  tilavarauspalvelu/models/reservation/model.py
  tilavarauspalvelu/models/reservation_statistic/model.py
Labels: improvement, breaking

#1512 Add background tasks for updating Pindora info on failure
  tests/test_tasks/test_create_missing_pindora_reservations.py
  tests/test_tasks/test_update_pindora_access_code_is_active.py
  tilavarauspalvelu/tasks.py
Labels: feature

#1513 Create an access code when approving a reservation without one
  tests/test_graphql_api/test_reservation/test_approve.py
  tests/test_graphql_api/test_reservation/test_requires_handling.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/approve_serializers.py
  tilavarauspalvelu/api/graphql/types/reservation/serializers/requires_handling_serializers.py
  tilavarauspalvelu/typing.py
Labels: improvement
