Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2025-03, with the labels that each got.

#1607 Update backend dependencies
  backend/poetry.lock
  backend/pyproject.toml
Labels: dependencies, python

#1627 Order ReservationUnitImages by `image_type`, remove unused `image_types`
  backend/locale/fi/LC_MESSAGES/django.po
  backend/locale/sv/LC_MESSAGES/django.po
  backend/tests/test_graphql_api/test_reservation_unit_image/test_ordering.py
  backend/tests/test_graphql_api/test_reservation_unit_image/test_update.py
  backend/tests/test_graphql_api/test_reservation_unit_image/test_update_permissions.py
  backend/tilavarauspalvelu/admin/reservation_unit_image/admin.py
  backend/tilavarauspalvelu/enums.py
  backend/tilavarauspalvelu/migrations/0070_reservation_unit_image_ordering.py
  backend/tilavarauspalvelu/models/reservation_unit_image/model.py
Labels: improvement

#1635 fix: missing reservation number in info card
  apps/ui/components/reservation/EditStep0.tsx
  apps/ui/components/reservation/EditStep1.tsx
  apps/ui/components/reservation/ReservationCancellation.tsx
  apps/ui/components/reservation/ReservationInfoCard.tsx
  apps/ui/pages/reservation-unit/[...params].tsx
  apps/ui/pages/reservations/[id]/confirmation.tsx
  apps/ui/pages/reservations/[id]/index.tsx
Labels: fix

#1637 Add series repair access code endpoint
  backend/tests/test_graphql_api/test_recurring_reservation/helpers.py
  backend/tests/test_graphql_api/test_recurring_reservation/test_repair_access_code.py
  backend/tests/test_graphql_api/test_recurring_reservation/test_repair_access_code_permissions.py
  backend/tilavarauspalvelu/api/graphql/mutations.py
  backend/tilavarauspalvelu/api/graphql/schema.py
  backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/mutations.py
  backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/repair_access_code.py
Labels: feature

#1639 Reschedule and then set active in Pindora series sync operation
  backend/tests/test_integrations/test_keyless_entry/test_pindora_service/test_sync_access_code.py
  backend/tilavarauspalvelu/integrations/keyless_entry/service.py
Labels: fix

#1651 Revert HAUKI Rewrite
  backend/tests/test_integrations/test_hauki/test_hauki_resource_hash_updater.py
  backend/tilavarauspalvelu/integrations/opening_hours/hauki_resource_hash_updater.py
  backend/tilavarauspalvelu/integrations/opening_hours/reservable_time_span_client.py
  backend/tilavarauspalvelu/models/origin_hauki_resource/model.py
Labels: fix

#1644 fix: display proper error message when reservation begins in future
  apps/ui/components/reservation-unit/Head.tsx
  apps/ui/modules/__tests__/reservation.test.ts
  apps/ui/modules/reservation.ts
  apps/ui/pages/reservation-unit/[id].tsx
Labels: fix

#1622 Remove time from reservation period in application round cards
  apps/ui/components/recurring/ApplicationRoundCard.tsx
Labels: fix

#1623 Replace min/maxPersons with personsAllowed
  apps/ui/components/FilterTagList.tsx
  apps/ui/components/SortingComponent.tsx
  apps/ui/components/application/ApplicationEvent.tsx
  apps/ui/components/application/ReservationUnitList.tsx
  apps/ui/components/application/ReservationUnitModalContent.tsx
  apps/ui/components/recurring/SeasonalSearchForm.tsx
  apps/ui/components/search/SingleSearchForm.tsx
  apps/ui/gql/gql-types.ts
  apps/ui/hooks/useOptions.ts
  apps/ui/modules/const.ts
  apps/ui/modules/queries/reservationUnit.tsx
  apps/ui/modules/search.ts
  apps/ui/public/locales/en/searchForm.json
  apps/ui/public/locales/fi/searchForm.json
  apps/ui/public/locales/sv/searchForm.json
Labels: improvement

#1678 fix: search fetch more
  apps/ui/hooks/useSearchQuery.tsx
  apps/ui/test/recurring/[id]/index.test.tsx
Labels: fix

#1646 Add access types to test data
  backend/tests/factories/reservation_unit.py
  backend/tests/factories/reservation_unit_access_type.py
  backend/tilavarauspalvelu/management/commands/data_creation/create_caisa.py
  backend/tilavarauspalvelu/management/commands/data_creation/create_reservation_units.py
  backend/tilavarauspalvelu/management/commands/data_creation/utils.py
Labels: improvement

#1667 Rewrite readme for monorepo
  README.md
  backend/README.md
Labels: improvement

#1653 Fix HAUKI opening hours fetching
  backend/tests/test_integrations/test_hauki/test_hauki_resource_hash_updater.py
  backend/tilavarauspalvelu/integrations/opening_hours/hauki_resource_hash_updater.py
  backend/tilavarauspalvelu/integrations/opening_hours/reservable_time_span_client.py
  backend/tilavarauspalvelu/models/origin_hauki_resource/model.py
Labels: fix

#1655 Fix HTML formatting for "access code unavailable instructions" in emails
  backend/templates/email/html/partials/access_code.jinja
  backend/templates/email/html/partials/access_code_with_instructions.jinja
  backend/templates/email/text/application_in_allocation.jinja
  backend/templates/email/text/partials/access_code.jinja
  backend/templates/email/text/partials/access_code_with_instructions.jinja
  backend/tests/test_integrations/test_email/test_email_types/test_reservation_approved.py
Labels: fix

#1654 Allow reservations that end in the future to be refunded
  backend/tests/test_graphql_api/test_reservation/test_refund.py
  backend/tilavarauspalvelu/models/reservation/validators.py
Labels: fix

#1675 Validate new applications are created during application period
  backend/tests/test_graphql_api/test_application/test_create.py
  backend/tests/test_graphql_api/test_application/test_update.py
  backend/tilavarauspalvelu/api/graphql/extensions/error_codes.py
  backend/tilavarauspalvelu/api/graphql/types/application/serializers.py
  backend/tilavarauspalvelu/models/application/validators.py
  backend/tilavarauspalvelu/models/application_round/validators.py
  backend/tilavarauspalvelu/models/user/validators.py
Labels: fix

#1683 Don't include access codes in emails if it is not actually active
  backend/tests/test_graphql_api/test_reservation/test_adjust_time.py
  backend/tests/test_graphql_api/test_reservation/test_confirm.py
  backend/tests/test_integrations/test_email/helpers.py
  backend/tests/test_integrations/test_email/test_email_types/test_reservation_approved.py
  backend/tests/test_integrations/test_email/test_email_types/test_reservation_confirmed.py
  backend/tests/test_integrations/test_email/test_email_types/test_reservation_modified.py
  backend/tests/test_integrations/test_email/test_email_types/test_reservation_modified_access_code.py
  backend/tests/test_integrations/test_email/test_email_types/test_seasonal_reservation_modified_series.py
  backend/tests/test_integrations/test_email/test_email_types/test_seasonal_reservation_modified_series_access_code.py
  backend/tilavarauspalvelu/admin/email_template/utils.py
  backend/tilavarauspalvelu/integrations/email/template_context/common.py
Labels: fix

#1658 Display access type & code in an approved application's reservation listing
  apps/ui/components/application/ApprovedReservations.tsx
  apps/ui/components/reservation-unit/Head.tsx
  apps/ui/gql/gql-types.ts
  apps/ui/modules/queries/fragments.tsx
  apps/ui/modules/queries/reservationUnit.tsx
  apps/ui/modules/reservationUnit.ts
  apps/ui/public/locales/en/application.json
  apps/ui/public/locales/en/common.json
  apps/ui/public/locales/en/reservations.json
  apps/ui/public/locales/fi/application.json
  apps/ui/public/locales/fi/common.json
  apps/ui/public/locales/fi/reservations.json
  apps/ui/public/locales/sv/application.json
  apps/ui/public/locales/sv/common.json
  apps/ui/public/locales/sv/reservations.json
Labels: feature

#1660 fix: access code section display in reservation view
  apps/ui/pages/reservations/[id]/index.tsx
Labels: fix

#1659 Display unrestricted access in reservation unit page infos
  apps/ui/components/reservation-unit/Head.tsx
Labels: fix

#1687 Fix test query count variable
  backend/tests/test_graphql_api/test_reservation_unit/test_query_first_reservable_time.py
Labels: fix
