Repository City-of-Helsinki/tilavarauspalvelu-core, pull requests merged in 2025-04, with the labels that each got.

#1695 fix: reporting codegen problems correctly
  README-ui.md
  package.json
Labels: fix

#1697 Add unit name to the application form time selector's reservation unit select element
  apps/ui/components/application/Page2.tsx
Labels: feature

#1700 Fix access code tooltip display condition
  apps/admin-ui/gql/gql-types.ts
  apps/admin-ui/src/spa/application-rounds/[id]/review/AllocatedEventsTable.tsx
  apps/admin-ui/src/spa/application-rounds/[id]/review/queries.tsx
Labels: fix

#1699 Limit application round reservation unit choices to seasonal bookable
  backend/tilavarauspalvelu/migrations/0072_alter_applicationround_reservation_units.py
  backend/tilavarauspalvelu/models/application_round/model.py
Labels: improvement

#1701 Fix email sending in series access code endpoints
  backend/tests/test_graphql_api/test_recurring_reservation/test_change_access_code.py
  backend/tests/test_graphql_api/test_recurring_reservation/test_repair_access_code.py
  backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/change_access_code.py
  backend/tilavarauspalvelu/api/graphql/types/recurring_reservation/serializers/repair_access_code.py
Labels: fix

#1702 fix: don't show null in application access type listing
  apps/ui/components/application/ApprovedReservations.tsx
Labels: fix

#1704 Remove permissions to access type fields on reservation
  backend/tilavarauspalvelu/api/graphql/types/reservation/types.py
Labels: fix

#1705 Run `update_access_types_for_reservations` when access types removed
  backend/tilavarauspalvelu/admin/reservation_unit/form.py
Labels: fix

#1708 Show code value if a multivalued access type includes access code
  apps/ui/components/application/ApprovedReservations.tsx
Labels: fix

#1709 fix: applications with "received" status shown correctly
  apps/ui/public/locales/fi/application.json
  packages/common/src/components/statuses/ApplicationStatusLabel.tsx
Labels: fix

#1711 fix: always show access code value in the dialog
  apps/ui/components/application/ApprovedReservations.tsx
Labels: fix

#1690 Add management command for defragmenting frontend queries
  backend/tilavarauspalvelu/management/commands/defragment_frontend_queries.py
Labels: feature

#1718 Fix missing reservation unit name in the card
  apps/ui/components/reservation/ReservationCard.tsx
  apps/ui/gql/gql-types.ts
Labels: fix

#1722 Fix beat scheduler reference
  backend/Makefile
  backend/config/celery/health_checks.py
  backend/docker/scheduler.sh
  backend/pyproject.toml
Labels: fix

#1730 fix: Error page translations
  apps/ui/pages/404.tsx
  apps/ui/pages/500.tsx
  apps/ui/pages/_error.tsx
  packages/common/src/components/ErrorContainer.tsx
Labels: fix

#1744 Add periodic tasks for pindora updates to test data
  backend/tilavarauspalvelu/management/commands/data_creation/create_misc.py
Labels: feature, improvement

#1746 Show Pindora info in django admin if future access type is access code
  backend/tilavarauspalvelu/admin/reservation_unit/form.py
  backend/tilavarauspalvelu/models/reservation_unit_access_type/queryset.py
Labels: fix

#1684 Don't allow adding new reservation units without active access type
  backend/tests/test_graphql_api/test_reservation_unit/test_access_types.py
  backend/tilavarauspalvelu/api/graphql/types/reservation_unit/serializers.py
Labels: feature

#1740 fix: Error page "give feedback" -> "contact us"
  apps/admin-ui/src/i18n/index.ts
  apps/admin-ui/src/i18n/locales/fi/errors.json
  apps/ui/public/locales/en/errors.json
  apps/ui/public/locales/fi/errors.json
  apps/ui/public/locales/sv/errors.json
  packages/common/src/components/ErrorContainer.tsx
Labels: fix
